<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * The showStars modifier shows stars in dependent of the score
 *
 * @param string $urlType      The url type (admin, user, etc.)
 * @param string $urlFunc      The url func (view, display, edit, etc.)
 * @param array  $urlArguments The argument array containing ids and other additional parameters
 *
 * @return string Desired url in encoded form.
 */
function smarty_modifier_reviewsShowStars($score)
{
    $result = '';
    
    switch ($score)
    {
        case (10):
            for ($i = 1; $i < 10; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
        case (9):
                for ($i = 1; $i < 9; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
        case (8):
                for ($i = 1; $i < 8; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
        case (7):
                for ($i = 1; $i < 7; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
        case (6):
                for ($i = 1; $i < 6; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
        case (5):
                for ($i = 1; $i < 5; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
        case (4):
                for ($i = 1; $i < 4; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
        case (3):
                for ($i = 1; $i < 3; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
        case (2):
                for ($i = 1; $i < 2; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
        case (1):
                for ($i = 1; $i < 1; $i++) {
                $result .= "<img src='/images/icons/extrasmall/favorites.png' />";
            }
            break;
            
            default:
                break;

    }

    return $result;
}
