<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Sat Aug 10 17:43:07 CEST 2013.
 */

/**
 * This is the Ajax controller class providing navigation and interaction functionality.
 */
class Reviews_Controller_Ajax extends Reviews_Controller_Base_Ajax
{
    // feel free to add your own controller methods here
}
