<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Sat Aug 10 17:43:09 CEST 2013.
 */

/**
 * Item selector plugin implementation class.
 */
class Reviews_Form_Plugin_ItemSelector extends Reviews_Form_Plugin_Base_ItemSelector
{
    // feel free to add your customisation here
}
