<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Fri Aug 09 17:57:06 CEST 2013.
 */

/**
 * Utility implementation class for controller helper methods.
 */
class Reviews_Util_Controller extends Reviews_Util_Base_Controller
{
	/**
	 * This function increment the page view if the user is not the creator
	 */

	public static function addView($id) 
	{
	    $serviceManager = ServiceUtil::getManager();
	    $modelHelper = new Reviews_Util_Model($serviceManager);
		// build review repository
		$repository = $modelHelper->getReviewRepository();

		$entity = $repository->selectById($id);

		$serviceManager = ServiceUtil::getManager();
		$entityManager = $serviceManager->getService('doctrine.entitymanager');

		if ($entity->getCreatedUserId() != UserUtil::getVar('uid')) {
		$hits = $entity->getHits();
		$entity->setHits($hits + 1);
		$email = $entity->getEmail();
		$email = html_entity_decode($email);
		$entity->setEmail($email);

		$entityManager->flush();
		}

		return true;

	}
}
