<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Sat Aug 10 17:43:07 CEST 2013.
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the concrete validation class for review entities.
 */
class Reviews_Entity_Validator_Review extends Reviews_Entity_Validator_Base_Review
{
    // here you can add custom validation methods or override existing checks
}
