<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de) at Sat Apr 19 16:49:58 CEST 2014.
 */

/**
 * Version information base class.
 */
class Reviews_Base_Version extends Zikula_AbstractVersion
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = array();
        // the current module version
        $meta['version']              = '2.5.0';
        // the displayed name of the module
        $meta['displayname']          = $this->__('Reviews');
        // the module description
        $meta['description']          = $this->__('Reviews module generated by ModuleStudio 0.6.2.');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('reviews');
        // core requirement
        $meta['core_min']             = '1.3.5'; // requires minimum 1.3.5
        $meta['core_max']             = '1.3.99'; // not ready for 1.4.0 yet

        // define special capabilities of this module
        $meta['capabilities'] = array(
                          HookUtil::SUBSCRIBER_CAPABLE => array('enabled' => true)/*,
                          HookUtil::PROVIDER_CAPABLE => array('enabled' => true), // TODO: see #15
                          'authentication' => array('version' => '1.0'),
                          'profile'        => array('version' => '1.0', 'anotherkey' => 'anothervalue'),
                          'message'        => array('version' => '1.0', 'anotherkey' => 'anothervalue')
*/
        );

        // permission schema
        $meta['securityschema'] = array(
            'Reviews::' => '::',
            'Reviews::Ajax' => '::',
            'Reviews:ItemListBlock:' => 'Block title::',
            'Reviews:ModerationBlock:' => 'Block title::',
            'Reviews:Review:' => 'Review ID::',
        );
        // DEBUG: permission schema aspect ends


        return $meta;
    }

    /**
     * Define hook subscriber bundles.
     */
    protected function setupHookBundles()
    {
        
        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.reviews.ui_hooks.reviews', 'ui_hooks', __('reviews Reviews Display Hooks'));
        
        // Display hook for view/display templates.
        $bundle->addEvent('display_view', 'reviews.ui_hooks.reviews.display_view');
        // Display hook for create/edit forms.
        $bundle->addEvent('form_edit', 'reviews.ui_hooks.reviews.form_edit');
        // Display hook for delete dialogues.
        $bundle->addEvent('form_delete', 'reviews.ui_hooks.reviews.form_delete');
        // Validate input from an ui create/edit form.
        $bundle->addEvent('validate_edit', 'reviews.ui_hooks.reviews.validate_edit');
        // Validate input from an ui create/edit form (generally not used).
        $bundle->addEvent('validate_delete', 'reviews.ui_hooks.reviews.validate_delete');
        // Perform the final update actions for a ui create/edit form.
        $bundle->addEvent('process_edit', 'reviews.ui_hooks.reviews.process_edit');
        // Perform the final delete actions for a ui form.
        $bundle->addEvent('process_delete', 'reviews.ui_hooks.reviews.process_delete');
        $this->registerHookSubscriberBundle($bundle);

        $bundle = new Zikula_HookManager_SubscriberBundle($this->name, 'subscriber.reviews.filter_hooks.reviews', 'filter_hooks', __('reviews Reviews Filter Hooks'));
        // A filter applied to the given area.
        $bundle->addEvent('filter', 'reviews.filter_hooks.reviews.filter');
        $this->registerHookSubscriberBundle($bundle);

        
    }
}
