<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Sat Aug 10 17:43:08 CEST 2013.
 */

/**
 * This handler class handles the page events of the Form called by the reviews_admin_edit() function.
 * It collects common functionality required by different object types.
 */
class Reviews_Form_Handler_Admin_Edit extends Reviews_Form_Handler_Admin_Base_Edit
{
    // feel free to extend the base handler class here
}
