<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Sat Aug 10 17:43:07 CEST 2013.
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing review categories.
 *
 * This is the concrete category class for review entities.
* @ORM\Entity(repositoryClass="Reviews_Entity_Repository_ReviewCategory")
   * @ORM\Table(name="reviews_review_category",
   *     uniqueConstraints={
   *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
   *     }
   * )
 */
class Reviews_Entity_ReviewCategory extends Reviews_Entity_Base_ReviewCategory
{
    // feel free to add your own methods here
}
