<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for review entities.
 */
class Reviews_Entity_Validator_Base_Review extends Reviews_Validator
{
    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array('message' => '', 'code' => 0, 'debugArray' => array());
        $dom = ZLanguage::getModuleDomain('Reviews');
        if (!$this->isValidInteger('id')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('id'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('id', 9)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('id', 9), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('workflowState')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('workflow state'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('title', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('title', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('title')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('title'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('text', 6000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('text', 6000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('text')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('text'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('zlanguage', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('zlanguage', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('zlanguage')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('zlanguage'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotContaining('zlanguage', ' ')) {
            $errorInfo['message'] = __f('Error! Field value must not contain space chars (%s).', array('zlanguage'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidLanguage('zlanguage', false)) {
            $errorInfo['message'] = __f('Error! Field value must be a valid language code (%s).', array('zlanguage'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('reviewer', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('reviewer', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('reviewer')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('reviewer'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('email', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('email', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('email')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('email'), $dom);
            return $errorInfo;
        }
        if (!$this->isValidEmail('email')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid email address (%s).', array('email'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('url', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('url', 255), $dom);
            return $errorInfo;
        }
        if ($this->entity['url'] != '' && !$this->isValidUrl('url')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid url (%s).', array('url'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('url_title', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('url_title', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('hits')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('hits'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('hits', 18)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('hits', 18), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('cover', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('cover', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('coverUpload', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('cover upload', 255), $dom);
            return $errorInfo;
        }
    
        return true;
    }
    
    /**
     * Check for unique values.
     *
     * This method determines if there already exist reviews with the same review.
     *
     * @param string $fieldName The name of the property to be checked
     * @return boolean result of this check, true if the given review does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if ($this->entity[$fieldName] === '') {
            return false;
        }
    
        $entityClass = 'Reviews_Entity_Review';
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository($entityClass);
    
        $excludeid = $this->entity['id'];
    
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }
    
    /**
     * Get entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set entity.
     *
     * @param Zikula_EntityAccess $entity.
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }
    
}
