<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Fri Aug 09 17:57:07 CEST 2013.
 */

/**
 * Upload handler implementation class.
 */
class Reviews_UploadHandler extends Reviews_Base_UploadHandler
{
    // feel free to add your upload handler enhancements here
}
