<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing review categories.
 *
 * This is the base category class for review entities.
 */
class Reviews_Entity_Base_ReviewCategory extends Zikula_Doctrine2_Entity_EntityCategory
{
    /**
     * @ORM\ManyToOne(targetEntity="Reviews_Entity_Review", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var Reviews_Entity_Review
     */
    protected $entity;
    
    /**
     * Get reference to owning entity.
     *
     * @return Reviews_Entity_Review
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set reference to owning entity.
     *
     * @param Reviews_Entity_Review $entity
     */
    public function setEntity(/*Reviews_Entity_Review */$entity)
    {
        $this->entity = $entity;
    }
}
