<?php
/**
 * Reviews.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package Reviews
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.0 (http://modulestudio.de) at Sat Aug 10 17:43:09 CEST 2013.
 */

/**
 * This class provides object meta data for the Tag module.
 */
class Reviews_TaggedObjectMeta_Reviews extends Reviews_TaggedObjectMeta_Base_Reviews
{
    // feel free to extend the tag support here
}
